import logging
from uuid import UUID
from sqlmodel import Session, select

from app.core.config import Settings
from app.services.v2.json_utils import parse_json_object
from app.services.v2.llm_clients.cloud import CloudLlmClient
from app.services.v2.llm_clients.local import LocalLlmClient
from app.services.v2.prompts import load_prompt
from app.services.v2.llm_clients import BaseLlmClient

logger = logging.getLogger(__name__)

# Only these are still LLM-generated per project. 'gate', 'rewriter', and
# 'synthesis' directly gate retrieval/answer correctness, so they are fixed,
# tested templates (see build_deterministic_prompts) with the project scope
# slotted in — never freeform LLM output. This keeps accuracy-critical
# instructions (JSON schema, "output only the query", the exact abstention
# string) from being silently dropped or reworded by a generation pass.
_REQUIRED_KEYS = ("generic", "decision", "visual_svg")

_PROJECT_SCOPE_TOKEN = "{{PROJECT_SCOPE}}"

_DECISION_REQUIRED_KEYS = ("verdict", "confidence", "feedback", "correct_route")

DEFAULT_SVG = (
    '<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">'
    '<rect width="100" height="100" rx="15" fill="#1f2937"/>'
    '<circle cx="50" cy="50" r="30" fill="#4b5563"/>'
    '<text x="50" y="55" font-family="system-ui" font-size="14" font-weight="bold" fill="#ffffff" text-anchor="middle">PROJ</text>'
    '</svg>'
)


def _project_scope(name: str, description: str) -> str:
    return f"{name.strip()} — {description.strip()}"


def build_deterministic_prompts(name: str, description: str) -> dict[str, str]:
    """Build the gate/rewriter/synthesis system prompts via fixed templates.

    These three prompts directly control retrieval and answer correctness,
    so they are never freeform-generated by an LLM (which can silently drop
    critical instructions, as observed with a per-project rewriter prompt
    missing its "output only the query" rule). Only the project scope text
    is substituted into an otherwise fixed, hand-tested instruction set.
    """
    scope = _project_scope(name, description)
    return {
        "gate": load_prompt("gate_template.txt").replace(_PROJECT_SCOPE_TOKEN, scope),
        "rewriter": load_prompt("rewriter_template.txt").replace(_PROJECT_SCOPE_TOKEN, scope),
        "synthesis": load_prompt("synthesis_template.txt").replace(_PROJECT_SCOPE_TOKEN, scope),
    }


def _default_generic_prompt(name: str, description: str) -> str:
    return (
        f'You are a conversational assistant for the project "{name.strip()}".\n'
        f"Your scope is strictly limited to: {description.strip()}\n"
        "If the user's query is unrelated to this scope, politely decline and explain what this assistant covers.\n"
        "Answer greetings, thanks, and small talk naturally.\n"
        "When conversation context is provided, each prior message has a UTC timestamp (oldest first). "
        "Prefer the latest turns for follow-ups."
    )


def _validate_and_repair(data: dict, name: str, description: str) -> dict[str, str]:
    """Safety net for the fields still generated by an LLM.

    A freeform generation pass can produce an empty/oversized persona prompt,
    a decision prompt missing its required JSON keys, or malformed SVG. Any
    of those failing validation falls back to a deterministic default rather
    than being persisted as-is.
    """
    repaired = dict(data)

    generic = str(data.get("generic", "")).strip()
    if not generic or len(generic) > 4000:
        logger.warning(
            "Generated 'generic' prompt failed validation (empty or oversized); using deterministic fallback."
        )
        repaired["generic"] = _default_generic_prompt(name, description)

    decision = str(data.get("decision", "")).strip()
    decision_lower = decision.lower()
    if not decision or not all(key in decision_lower for key in _DECISION_REQUIRED_KEYS):
        logger.warning(
            "Generated 'decision' prompt failed validation (missing required JSON keys); using default template."
        )
        repaired["decision"] = load_prompt("decision_agent_system.txt")

    svg = str(data.get("visual_svg", "")).strip()
    if not (svg.startswith("<svg") and "</svg>" in svg):
        logger.warning(
            "Generated 'visual_svg' failed validation (not well-formed SVG); using default placeholder."
        )
        repaired["visual_svg"] = DEFAULT_SVG

    return repaired

def _build_system_instruction(name: str, description: str) -> str:
    decision_template = load_prompt("decision_agent_system.txt")

    return (
        "You are an expert prompt engineer. Your task is to generate customized system prompts "
        "for two agents plus a visual asset in a RAG-powered chatbot pipeline named Scrutinize.\n\n"
        "Project details:\n"
        f"- Project Name: {name}\n"
        f"- Project Description (also defines in-scope topics and refusal boundaries): {description}\n\n"
        "NOTE: the retrieval-critical agents ('gate', 'rewriter', 'synthesis') are NOT generated by you — "
        "they use fixed, pre-tested instruction templates elsewhere in the system, because those three "
        "directly control search accuracy and must never have their instructions altered or dropped. "
        "You only generate the two agents below, whose behavior is persona/tone-facing rather than "
        "retrieval-critical.\n\n"
        "Agent responsibilities:\n"
        "1. 'generic': Handles greetings, small talk, and out-of-scope questions. It MUST politely "
        "decline questions outside the project description scope, briefly explaining what this "
        "assistant covers instead.\n"
        "2. 'decision': Evaluates whether routing and the draft answer were correct; verdict is "
        "'good' or 'retry'.\n\n"
        "CRITICAL — the generated 'decision' prompt MUST instruct the agent to return JSON only using "
        "this exact schema (adapt evaluation rules to the project, but keep keys and enum values unchanged):\n"
        f"{decision_template}\n\n"
        "The decision prompt MUST explain how to evaluate PDF/document/flowchart/tool requests and when to "
        "retry with correct_route \"rag\".\n\n"
        "You MUST return a JSON object with exactly the keys: 'generic', 'decision', 'visual_svg'. "
        "Each value must be the full system prompt string for that agent, except 'visual_svg' which must "
        "be a valid, raw, modern, beautiful, and self-contained SVG code representing the project visually "
        "based on the project name and description.\n"
        "SVG Design Guidelines:\n"
        "- Must use viewBox='0 0 200 150' to fit the card header aspect ratio.\n"
        "- First of all, read the project name and description.\n"
        "- If it is an object, company, or anything, find the main color of that thing. For example, NVIDIA's main color is green, so the background of the SVG must be green or have green as the primary background/color theme.\n"
        "- If the mentioned project name and description is about a company or a person, find their famous identity (such as their logo, face shape, or most connected community logo) and visualize it in the center or main path of the SVG.\n"
        "- If anything extra about that main topic is mentioned in the project, try to visualize it in the SVG as side elements/details surrounding the main logo or identity.\n"
        "- Do NOT draw simple shapes, plain text, or basic clip art. Create a highly creative, sophisticated, and modern digital vector artwork.\n"
        "- Use rich, vibrant gradient maps (define multi-stop <linearGradient> or <radialGradient> with high-end color transitions in a <defs> block) instead of flat, solid colors.\n"
        "- Use organic curves, flowing wave paths, and complex bezier shapes (<path d='...' />) to draw custom artwork rather than basic rectangles and circles.\n"
        "- Incorporate glowing aura and dimension effects. Define `<filter id='glow'>` in the defs containing `<feGaussianBlur>` and `<feMerge>` elements to make parts of the vector glow.\n"
        "- Use layered translucent glassmorphic plates (shapes with `fill-opacity='0.15'` up to `0.45` and subtle borders) overlapping each other to create stunning depth.\n"
        "- Forbid low-effort designs, centered single shapes, emojis, or flat cartoons. The SVG must look like a premium digital asset created by a professional designer.\n"
        "- Do not wrap the SVG string in markdown code block ticks inside the JSON value."
    )


def _generate_persona_prompts(name: str, description: str, settings: Settings) -> dict:
    """LLM-generate only the persona/tone-facing fields: generic, decision, visual_svg.

    Falls back to cloud -> local -> None (caller applies deterministic defaults).
    Returns raw, unvalidated LLM output — callers must run it through
    _validate_and_repair before trusting any field.
    """
    system_instruction = _build_system_instruction(name, description)
    user_prompt = (
        f"Generate the JSON object containing the two system prompts and the visual SVG.\n\n"
        f"CRITICAL: For the 'visual_svg' key, you must design custom artwork that directly represents "
        f"the project '{name}' and its description: '{description}'. "
        f"Analyze the name and description, identify the core theme/domain, and construct a beautiful, "
        f"thematic vector illustration representing that specific domain. Do not make it generic."
    )

    try:
        logger.info("Attempting to generate project persona prompts using cloud LLM 'gpt-4o'...")
        cloud_client = CloudLlmClient(settings)
        response = cloud_client.generate(
            model="gpt-4o",
            system=system_instruction,
            user=user_prompt,
            json_mode=True,
        )
        data = parse_json_object(response.content)
        if all(k in data for k in _REQUIRED_KEYS):
            logger.info("Successfully generated project persona prompts using cloud LLM.")
            return {key: str(data[key]) for key in _REQUIRED_KEYS}
        logger.warning("Cloud LLM returned incomplete JSON keys: %s", data.keys())
    except Exception as exc:
        logger.warning("Failed to generate persona prompts using cloud LLM: %s. Trying local LLM fallback...", exc)

    if settings.local_llm_base_url:
        try:
            logger.info("Attempting to generate project persona prompts using local LLM fallback 'qwen3.5:2b'...")
            local_client = LocalLlmClient(settings)
            response = local_client.generate(
                model="qwen3.5:2b",
                system=system_instruction,
                user=user_prompt,
                json_mode=True,
            )
            data = parse_json_object(response.content)
            if all(k in data for k in _REQUIRED_KEYS):
                logger.info("Successfully generated project persona prompts using local LLM fallback.")
                return {key: str(data[key]) for key in _REQUIRED_KEYS}
            logger.warning("Local LLM fallback returned incomplete JSON keys: %s", data.keys())
        except Exception as local_exc:
            logger.error("Failed to generate persona prompts using local LLM fallback: %s", local_exc)

    return {}


def generate_project_prompts(
    name: str,
    description: str,
    settings: Settings,
) -> dict[str, str]:
    """
    Builds the system prompts for all five agent types: gate, rewriter, generic,
    synthesis, decision — plus the visual SVG.

    'gate', 'rewriter', and 'synthesis' are deterministic (fixed, pre-tested
    templates with the project scope slotted in) since they directly control
    retrieval and answer correctness and must never be freeform-generated.
    'generic', 'decision', and 'visual_svg' are persona/tone-facing and are
    still LLM-generated (cloud 'gpt-4o' first, local fallback second), but
    always pass through validation with a deterministic fallback per field —
    a failed or missing generation never blocks project creation or leaves an
    agent without a working prompt.
    """
    deterministic = build_deterministic_prompts(name, description)

    generated = _generate_persona_prompts(name, description, settings)
    if not generated:
        logger.error(
            "Both cloud and local LLM generation failed for persona prompts; "
            "using deterministic-only fallback for generic/decision/visual_svg."
        )
    validated = _validate_and_repair(generated, name, description)

    return {
        **deterministic,
        "generic": validated["generic"],
        "decision": validated["decision"],
        "visual_svg": validated["visual_svg"],
    }


def recreate_project_svg(
    project_id: UUID,
    session: Session,
    settings: Settings,
    llm: BaseLlmClient,
) -> None:
    """
    Fetches context (recent messages) in this project and triggers Cloud LLM to
    regenerate a new visual SVG representation, saving it to project settings.
    """
    from app.models.project import Project
    from app.models.conversation import ChatConversation, ChatMessage

    project = session.get(Project, project_id)
    if not project:
        logger.warning("Project %s not found for SVG recreation", project_id)
        return

    # Get the last 10 messages for context
    recent_messages = session.exec(
        select(ChatMessage)
        .join(ChatConversation, ChatMessage.conversation_id == ChatConversation.id)
        .where(ChatConversation.project_id == project_id)
        .where(ChatMessage.status == "completed")
        .where(ChatMessage.role.in_(["user", "assistant"]))
        .order_by(ChatMessage.created_at.desc())
        .limit(10)
    ).all()

    # Reverse to chronological order
    recent_messages.reverse()

    # Build context string
    history_text = "\n".join(f"{m.role}: {m.content}" for m in recent_messages)

    system_instruction = (
        "You are a professional designer. Your task is to generate a beautiful, modern, clean, "
        "and self-contained SVG image that visually represents a project based on its title, "
        "description, and recent chat history.\n\n"
        "Project details:\n"
        f"- Project Name: {project.name}\n"
        f"- Project Description: {project.settings.get('description', '')}\n\n"
        "Recent conversation context to inspire the design update:\n"
        f"{history_text}\n\n"
        "SVG Requirements:\n"
        "- Must be valid, raw, modern, beautiful, and clean SVG code.\n"
        "- Must use viewBox='0 0 200 150' to fit the card header aspect ratio.\n"
        "- First of all, read the project name and description.\n"
        "- If it is an object, company, or anything, find the main color of that thing. For example, NVIDIA's main color is green, so the background of the SVG must be green or have green as the primary background/color theme.\n"
        "- If the mentioned project name and description is about a company or a person, find their famous identity (such as their logo, face shape, or most connected community logo) and visualize it in the center or main path of the SVG.\n"
        "- If anything extra about that main topic is mentioned in the project, try to visualize it in the SVG as side elements/details surrounding the main logo or identity.\n"
        "- Do NOT draw simple shapes, plain text, or basic clip art. Create a highly creative, sophisticated, and modern digital vector artwork.\n"
        "- Use rich, vibrant gradient maps (define multi-stop <linearGradient> or <radialGradient> with high-end color transitions in a <defs> block) instead of flat, solid colors.\n"
        "- Use organic curves, flowing wave paths, and complex bezier shapes (<path d='...' />) to draw custom artwork rather than basic rectangles and circles.\n"
        "- Incorporate glowing aura and dimension effects. Define `<filter id='glow'>` in the defs containing `<feGaussianBlur>` and `<feMerge>` elements to make parts of the vector glow.\n"
        "- Use layered translucent glassmorphic plates (shapes with `fill-opacity='0.15'` up to `0.45` and subtle borders) overlapping each other to create stunning depth.\n"
        "- Forbid low-effort designs, centered single shapes, emojis, or flat cartoons. The SVG must look like a premium digital asset created by a professional designer.\n"
        "- Do not include markdown code block formatting (such as ```xml or ```svg).\n"
        "- Output ONLY the raw SVG code. No explanations, no JSON, no prefix, no suffix."
    )

    try:
        logger.info("Attempting to regenerate visual SVG using Cloud LLM gpt-4o...")
        cloud_client = CloudLlmClient(settings)
        response = cloud_client.generate(
            model="gpt-4o",
            system=system_instruction,
            user="Generate the new updated visual SVG representation.",
        )
        svg_code = response.content.strip()
        # Clean up code blocks if LLM accidentally wrapped it
        if "```" in svg_code:
            lines = svg_code.splitlines()
            cleaned_lines = [l for l in lines if not l.strip().startswith("```")]
            svg_code = "\n".join(cleaned_lines).strip()
    except Exception as exc:
        logger.error("Failed to regenerate SVG using Cloud LLM: %s. Falling back to provided llm...", exc)
        try:
            response = llm.generate(
                model="gpt-4o",
                system=system_instruction,
                user="Generate the new updated visual SVG representation.",
            )
            svg_code = response.content.strip()
            if "```" in svg_code:
                lines = svg_code.splitlines()
                cleaned_lines = [l for l in lines if not l.strip().startswith("```")]
                svg_code = "\n".join(cleaned_lines).strip()
        except Exception as fallback_exc:
            logger.error("Fallback LLM also failed to regenerate SVG: %s", fallback_exc)
            return

    if svg_code.startswith("<svg") and "</svg>" in svg_code:
        project_settings = dict(project.settings)
        project_settings["visual_svg"] = svg_code
        project.settings = project_settings
        session.add(project)
        session.commit()
        logger.info("Successfully updated visual SVG for project %s", project_id)
    else:
        logger.warning("Generated text does not seem to contain a valid SVG: %s", svg_code[:100])

